@host = http://localhost
@port = 3000
@url = {{host}}:{{port}}


###get kategories

GET {{url}}/categories
Content-Type: application/json




### Get one kategory by id

GET {{url}}/categories/3
Content-Type: application/json

### Delete one kategory by id

DELETE {{url}}/categories/4
Content-Type: application/json

### Post kategories

POST{{url}}/categories
Content-Type: application/json

{
    "nev": "Desszertek"
}




### Patch kategory by id

PATCH http://localhost:3000/categories/1
Content-Type: application/json

{
    "nev": "Ételek"
}

