### Get product buyers
GET http://localhost:3000/product
Content-Type: application/json

###Get product by id
GET http://localhost:3000/product/247
Content-Type: application/json

### Post new product
POST http://localhost:3000/product
Content-Type: application/json

{
    "nev": "Fánk",
    "categoryID": 2,
    "egyseg" : "db" ,
    "ar": 250
}

### Update product
PATCH http://localhost:3000/product/1
Content-Type: application/json

{
    "nev": "Túrós csusza",
    "categoryID":2,
    "egyseg": "adag",
    "ar": 1200
}