###get traffiec

GET http://localhost:3000/trafics
Content-Type: application/json



### Get one forgalom by id

GET http://localhost:3000/trafics/247
Content-Type: application/json

### Delete one forgalom by id

GET http://localhost:3000/trafics/3
Content-Type: application/json

### Post kategories

POST http://localhost:3000/trafics
Content-Type: application/json

{
    "termek": "Lángos",
    "vevo": "Lajos",
    "kategoriaId": 1,
    "egyeseg" : ,
    "mennyiseg":,
    "kiadva":
}


### Patch forgalom by id

PATCH http://localhost:3000/trafics/247
Content-Type: application/json

{
     "termek": "Lángos",
    "vevo": "Lajos",
    "kategoriaId": 1,
    "egyeseg" :3 ,
    "mennyiseg":3,
    "kiadva":1
}