@host = http://localhost
@port = 3000
@url = {{host}}:{{port}}

###get traffiec

GET {{url}}/trafics
Content-Type: application/json



### Get one forgalom by id

GET {{url}}/trafics/247
Content-Type: application/json

### Delete one forgalom by id

GET {{url}}/trafics/3
Content-Type: application/json

### Post traific

POST {{url}}/trafics
Content-Type: application/json

{
    "termek": "Lángos",
    "vevo": "Lajos",
    "kategoriaId": 1,
    "egyseg" :3 ,
    "mennyiseg":3,
    "nettoar": 9,
    "kiadva":1
}


### Patch forgalom by id

PATCH {{url}}/trafics/247
Content-Type: application/json

{
    "termek": "Lángos",
    "vevo": "Lajos",
    "kategoriaId": 1,
    "egyeseg" : "db" ,
    "nettoar": 9,
    "mennyiseg":3,
    "kiadva":1
}

### Get trafics buyers

GET {{url}}/trafics/buyers
Content-Type: application/json